from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

#!!!!!!!SELECT MODE !!!!!!!!!!!

MODE = "DEVELOPMENT"

#close all open positions and orders
ABORT_ALL_POSITIONS = False

#find cointigrated pairs
FIND_COINTEGRATED = True

#place trades
PLACE_TRADES = True

#resolution
RESOLUTION = "1 HOUR"

#stats window
WINDOW = 21

#tresh holds opening

MAX_HALF_LIFE = 24
ZSCORE_TRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL= 1881

#tresh holds closing

CLOSE_AT_ZSCORE_CROSS = True

#etherium adress
ETHEREUM_ADDRESS = "0xE115fF834536e3BBB927B10E424f90ae5B8aB87B"

#KEYS - Production
#Must to be on mainnet on DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

#KEYS - Development
#Must to be on testnet on DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

#KEYS -Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

#HOST export

HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

#HTTP PROVIDER 

HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/a2l3dkS1SaREF24h20VQNx2ekhel8t7u" 
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/d4dMR-z8AnIthql5B1hZEAwDnN3LvOAl"

HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET